Repository openfun/openedx-docker, pull requests merged in 2019-12, with the labels that each got.

#143 Fix CI job names and execution
  .circleci/config.yml
  bin/ci
Labels: improvement, needs review

#146 🐛(circle) fix bin/ci checkpoint
  bin/ci
Labels: bug, critical, needs review

#148 🐛(docker) fix typo in redis-sentinel env file
  env.d/redis-sentinel
Labels: bug

#152 🔧(dogwood/3/fun) add Glowbl xblock settings
  releases/dogwood/3/fun/CHANGELOG.md
  releases/dogwood/3/fun/config/cms/fun.py
  releases/dogwood/3/fun/config/lms/fun.py
Labels: improvement, needs review

#159 🔧(*/flavors) configure `general` memcached cache backend
  releases/dogwood/3/bare/CHANGELOG.md
  releases/dogwood/3/bare/config/cms/docker_run_production.py
  releases/dogwood/3/bare/config/lms/docker_run_production.py
  releases/dogwood/3/fun/CHANGELOG.md
  releases/dogwood/3/fun/config/cms/docker_run_production.py
  releases/dogwood/3/fun/config/lms/docker_run_production.py
  releases/eucalyptus/3/bare/CHANGELOG.md
  releases/eucalyptus/3/bare/config/cms/docker_run_production.py
  releases/eucalyptus/3/bare/config/lms/docker_run_production.py
  releases/eucalyptus/3/wb/CHANGELOG.md
  releases/eucalyptus/3/wb/config/cms/docker_run_production.py
  releases/eucalyptus/3/wb/config/lms/docker_run_production.py
  releases/hawthorn/1/bare/CHANGELOG.md
  releases/hawthorn/1/bare/config/cms/docker_run_production.py
  releases/hawthorn/1/bare/config/lms/docker_run_production.py
  releases/hawthorn/1/oee/CHANGELOG.md
  releases/hawthorn/1/oee/config/cms/docker_run_production.py
  releases/hawthorn/1/oee/config/lms/docker_run_production.py
  releases/master/bare/config/cms/docker_run_production.py
  releases/master/bare/config/lms/docker_run_production.py
Labels: bug, critical

#160 🔖(dogwood/3/fun) bump to dogwood.3-fun-1.3.7
  releases/dogwood/3/fun/CHANGELOG.md
Labels: FUN, bug, critical

#163 🐛(project) ensure the clean target never fails
  Makefile
Labels: improvement, needs review
