Repository openfun/openedx-docker, pull requests merged in 2019-10, with the labels that each got.

#124 🐛(hawthorn/1/oee) restore instructor exports
  Makefile
  docker-compose.yml
  releases/hawthorn/1/oee/CHANGELOG.md
  releases/hawthorn/1/oee/entrypoint.sh
Labels: bug, needs review

#125 🔧(config) add LOCALE_PATHS to configurable settings
  releases/dogwood/3/bare/CHANGELOG.md
  releases/dogwood/3/bare/config/cms/docker_run_production.py
  releases/dogwood/3/bare/config/lms/docker_run_production.py
  releases/hawthorn/1/bare/CHANGELOG.md
  releases/hawthorn/1/bare/config/cms/docker_run_production.py
  releases/hawthorn/1/bare/config/lms/docker_run_production.py
  releases/hawthorn/1/oee/CHANGELOG.md
  releases/hawthorn/1/oee/config/cms/docker_run_production.py
  releases/hawthorn/1/oee/config/lms/docker_run_production.py
  releases/master/bare/config/cms/docker_run_production.py
  releases/master/bare/config/lms/docker_run_production.py
Labels: improvement

#126 ⬆️(hawthorn/1/oee) upgrade fonzie to 0.2.1
  releases/hawthorn/1/oee/CHANGELOG.md
  releases/hawthorn/1/oee/requirements.txt
Labels: bug

#129 🔖(hawthorn/1/oee) bump to hawthorn.1-oee-2.10.0
  releases/hawthorn/1/oee/CHANGELOG.md
Labels: FUN, bug

#127 🔖(hawthorn/1/bare) bump to hawthorn.1-2.7.0
  releases/hawthorn/1/bare/CHANGELOG.md
Labels: improvement

#128 🔖(dogwood/3/bare) bump to dogwood.3-1.1.0
  releases/dogwood/3/bare/CHANGELOG.md
Labels: improvement

#131 🐛(master|hawthorn/1/*) fix LOCALE_PATHS override
  releases/hawthorn/1/bare/CHANGELOG.md
  releases/hawthorn/1/bare/config/lms/docker_run_production.py
  releases/hawthorn/1/oee/CHANGELOG.md
  releases/hawthorn/1/oee/config/lms/docker_run_production.py
  releases/master/bare/config/lms/docker_run_production.py
Labels: bug, critical, needs review
