Repository openfun/openedx-docker, pull requests merged in 2020-01, with the labels that each got.

#172 ♻️(flavors/*) make ORA2 configurable on all flavors
  releases/dogwood/3/bare/CHANGELOG.md
  releases/dogwood/3/bare/config/lms/docker_run_production.py
  releases/dogwood/3/fun/config/lms/docker_run_production.py
  releases/eucalyptus/3/bare/CHANGELOG.md
  releases/eucalyptus/3/bare/config/lms/docker_run_production.py
  releases/eucalyptus/3/wb/CHANGELOG.md
  releases/eucalyptus/3/wb/config/lms/docker_run_production.py
  releases/hawthorn/1/bare/CHANGELOG.md
  releases/hawthorn/1/bare/config/lms/docker_run_production.py
  releases/hawthorn/1/oee/CHANGELOG.md
  releases/hawthorn/1/oee/config/lms/docker_run_production.py
  releases/master/bare/config/lms/docker_run_production.py
Labels: improvement

#173 🔧(*/flavors) configure default cache backends
  releases/dogwood/3/bare/CHANGELOG.md
  releases/dogwood/3/bare/config/cms/docker_run_production.py
  releases/dogwood/3/bare/config/lms/docker_run_production.py
  releases/dogwood/3/fun/CHANGELOG.md
  releases/dogwood/3/fun/config/cms/docker_run_production.py
  releases/dogwood/3/fun/config/lms/docker_run_production.py
  releases/eucalyptus/3/bare/CHANGELOG.md
  releases/eucalyptus/3/bare/config/cms/docker_run_production.py
  releases/eucalyptus/3/bare/config/lms/docker_run_production.py
  releases/eucalyptus/3/wb/CHANGELOG.md
  releases/eucalyptus/3/wb/config/cms/docker_run_production.py
  releases/eucalyptus/3/wb/config/lms/docker_run_production.py
  releases/hawthorn/1/bare/CHANGELOG.md
  releases/hawthorn/1/bare/config/cms/docker_run_production.py
  releases/hawthorn/1/bare/config/lms/docker_run_production.py
  releases/hawthorn/1/oee/CHANGELOG.md
  releases/hawthorn/1/oee/config/cms/docker_run_production.py
  releases/hawthorn/1/oee/config/lms/docker_run_production.py
  releases/master/bare/config/cms/docker_run_production.py
  releases/master/bare/config/lms/docker_run_production.py
Labels: FUN, improvement

#166 ✨([dogwood|eucalyptus]/3/[fun|wb]) activate studio's `videoupload` page
  releases/dogwood/3/fun/CHANGELOG.md
  releases/dogwood/3/fun/config/cms/docker_run_production.py
  releases/eucalyptus/3/wb/CHANGELOG.md
  releases/eucalyptus/3/wb/config/cms/docker_run_production.py
Labels: FUN, feature

#178 🔥(eucalyptus/3/*) remove settings related to cross-process queues
  releases/eucalyptus/3/bare/CHANGELOG.md
  releases/eucalyptus/3/bare/config/cms/docker_run_production.py
  releases/eucalyptus/3/bare/config/lms/docker_run_production.py
  releases/eucalyptus/3/wb/CHANGELOG.md
  releases/eucalyptus/3/wb/config/cms/docker_run_production.py
  releases/eucalyptus/3/wb/config/lms/docker_run_production.py
Labels: easy pick

#180 🐛(eucalyptus/3/wb) neutralize thumbnails creation as they are not used
  releases/eucalyptus/3/wb/CHANGELOG.md
  releases/eucalyptus/3/wb/config/lms/docker_run_production.py
Labels: bug

#177 🐛(flavors/*) Ensure all required directories exists inside each volume
  releases/dogwood/3/bare/CHANGELOG.md
  releases/dogwood/3/bare/config/lms/docker_run_production.py
  releases/dogwood/3/bare/config/lms/utils.py
  releases/dogwood/3/fun/CHANGELOG.md
  releases/dogwood/3/fun/config/lms/docker_run_development.py
  releases/dogwood/3/fun/config/lms/docker_run_production.py
  releases/dogwood/3/fun/config/lms/utils.py
  releases/eucalyptus/3/bare/CHANGELOG.md
  releases/eucalyptus/3/bare/config/lms/docker_run_production.py
  releases/eucalyptus/3/bare/config/lms/utils.py
  releases/eucalyptus/3/wb/CHANGELOG.md
  releases/eucalyptus/3/wb/config/lms/docker_run_production.py
  releases/eucalyptus/3/wb/config/lms/utils.py
  releases/hawthorn/1/bare/CHANGELOG.md
  releases/hawthorn/1/bare/config/lms/docker_run_production.py
  releases/hawthorn/1/bare/config/lms/utils.py
  releases/hawthorn/1/oee/CHANGELOG.md
  releases/hawthorn/1/oee/config/lms/docker_run_production.py
  releases/hawthorn/1/oee/config/lms/utils.py
  releases/master/bare/config/lms/docker_run_production.py
  releases/master/bare/config/lms/utils.py
Labels: bug

#181 🐛([dogwood|eucalyptus]/3/[fun|wb]) fix videofront subtitles cache
  releases/dogwood/3/fun/config/cms/docker_run_production.py
  releases/dogwood/3/fun/config/lms/docker_run_production.py
  releases/eucalyptus/3/wb/config/cms/docker_run_production.py
  releases/eucalyptus/3/wb/config/lms/docker_run_production.py
Labels: bug

#187 🐛(dogwood/3/fun) Fix known unpacking bug in xmodule
  releases/dogwood/3/fun/CHANGELOG.md
  releases/dogwood/3/fun/Dockerfile
  releases/dogwood/3/fun/activate
Labels: FUN, bug

#188 🔧(dogwood/3/fun) rewrite constants related to fun's PDF certificates urls
  releases/dogwood/3/fun/CHANGELOG.md
  releases/dogwood/3/fun/Dockerfile
  releases/dogwood/3/fun/activate
  releases/dogwood/3/fun/config/lms/docker_run_production.py
  releases/dogwood/3/fun/requirements.txt
Labels: FUN, bug

#191 🔖(eucalyptus/3/wb) bump to eucalyptus.3-wb-1.6.2
  releases/eucalyptus/3/wb/CHANGELOG.md
Labels: FUN, needs review

#192 🔖(hawthorn/1/oee) bump to hawthorn.1-oee-3.1.1
  releases/hawthorn/1/oee/CHANGELOG.md
Labels: FUN, needs review
